controllers/HomeController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\controllers;


use app\behaviors\Access;
use app\modules\invoice\models\Invoice;
use app\models\User;
use app\helpers\SQL;
use Yii;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class HomeController extends Controller {

    public function behaviors() {
        return [
            'access' => [
                'class' => Access::class,
                'manager' => ['settings'],
            ]
        ];
    }

    public function actionIndex() {
        return $this->render('index', [
            'statistics' => $this->renderPartial('statistics', ['statistics' => static::statistics()])
        ]);
    }

    public function actionSettings() {
        $settings = SQL::queryArray('SELECT * FROM var ORDER BY name');
        if (!empty($_POST)) {
            foreach($_POST as $key => $value) {
                if ('_' == $key[0]) {
                    continue;
                }
                $params = [
                    ':name' => $key,
                    ':value' => empty($value) ? null : $value
                ];

                if (!isset($settings[$key])) {
                    SQL::query('INSERT INTO var VALUES (:name, :value)', $params);
                }
                elseif ($value != $settings[$key]) {
                    SQL::query('UPDATE var SET value = :value WHERE name = :name', $params);
                }

                $settings[$key] = $value;
            }
        }
        return $this->render('settings', [
            'settings' => $settings
        ]);
    }

    public function actionError() {
        $exception = Yii::$app->getErrorHandler()->exception;
        $message = $exception->getMessage();
        if ($exception instanceof ForbiddenHttpException) {
            $message = $message ? Yii::t('app', $message) : Yii::t('app', 'Forbidden');
        }
        if ($message) {
            Yii::$app->session->setFlash('error', $message);
        }
        return $this->render('error', [
            'exception' => $exception
        ]);
    }

    public static function statistics() {
        $started = strtotime(SQL::queryCell('SELECT "time" FROM "journal" WHERE id = 1'));
        $invested = (int) SQL::queryCell('SELECT count(*) FROM "node"');
        return [
            'Started' => date('d-m-Y', $started),
            'Running days' => floor((time() - $started)/(3600 * 24)),
            'Users' => User::find()->count(),
            'Total deposited' => Invoice::find()->where(['or',
                ['status' => 'success'],
                ['status' => 'delete']
            ])->andWhere('amount > 0')->sum('amount'),
            'Total withdraw' => - Invoice::find()->where(['or',
                ['status' => 'success'],
                ['status' => 'delete']
            ])->andWhere('amount < 0')->sum('amount'),
            'Number of investments' => $invested
        ];
    }
}

controllers/UserController.php
<?php
/**
 * @link http://zenothing.com/
 */

namespace app\controllers;

use app\behaviors\Access;
use app\behaviors\Journal;
use app\models\Login;
use app\models\Password;
use app\models\Record;
use app\models\ResetRequest;
use app\helpers\SQL;
use app\modules\pyramid\models\Node;
use app\modules\pyramid\models\Type;
use Yii;
use app\models\User;
use app\models\search\User as UserSearch;
use yii\base\InvalidParamException;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * @author Taras Labiak <kissarat@gmail.com>
 */
class UserController extends Controller
{
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                ],
            ],

            'access' => [
                'class' => Access::class,
                'plain' => ['view', 'update', 'index'],
                'manager' => ['complete', 'account'],
                'admin' => ['create', 'delete']
            ]
        ];
    }

    public function actionIndex() {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($name = null) {
        /* @var User $me */
        $me = Yii::$app->user->identity;
        $model = $name ? $this->findModel($name) : $me;
        if (!$name || $me->isManager() || $model->ref_name == $name || User::find()->where([
                'ref_name' => $me->name, 'name' => $name])->count() > 0) {
            return $this->render('view', [
                'model' => $model,
            ]);
        }
        throw new ForbiddenHttpException();
    }

    public function actionCreate() {
        $model = new User([
            'account' => 0
        ]);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'name' => $model->name]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'bundle' => []
            ]);
        }
    }

    public function actionUpdate($name) {
        $model = $this->findModel($name);

        if ($model->name != Yii::$app->user->identity->name && !Yii::$app->user->identity->isAdmin()) {
            throw new ForbiddenHttpException('Forbidden');
        }

        if ($model->load(Yii::$app->request->post())) {
            if (!Yii::$app->user->identity->isAdmin()) {
                if ($model->isAttributeChanged('email', false)) {
                    $model->generateCode();
                    $url = Url::to(['email', 'code' => $model->code], true);
                    $model->sendEmail([
                        'subject' => Yii::$app->params['site']['name'] . ' ' . Yii::t('app', 'Email confirmation'),
                        'content' => Yii::t('app', 'To confirm your email click on the <a href="{url}">link</a>', [
                            'url' => $url,
                        ])
                    ]);
                    $model->setBundle(['email' => $model->email]);
                    $model->email = $model->getOldAttribute('email');
                    Yii::$app->session->setFlash('info', Yii::t('app', 'The new email address will be changed after you confirm it'));
                }
                if ($model->isAttributeChanged('perfect', false)) {
                    $model->perfect = $model->getOldAttribute('perfect');
                    Yii::$app->session->setFlash('error', Yii::t('app', 'Wallet can change admin only'));
                }
            }

            if ('Europe/Moscow' == $model->timezone) {
                $model->timezone = null;
            }

            foreach(['skype', 'country', 'phone', 'forename', 'surname'] as $name) {
                if (empty($model->$name)) {
                    $model->$name = null;
                }
            }

            if (Yii::$app->user->identity->name == $model->name && $model->isAttributeChanged('timezone', false)) {
                $_SESSION['timezone'] = $model->timezone;
            }

            if ($model->save()) {
                if (Yii::$app->user->identity->isAdmin()) {
                    return $this->redirect(['view', 'name' => $model->name]);
                }
                else {
                    return $this->redirect(['view']);
                }
            }
        }

        if (!$model->timezone) {
            $model->timezone = 'Europe/Moscow';
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionDelete($name) {
        $this->findModel($name)->delete();
        return $this->redirect(['index']);
    }

    /**
     * @param string $name
     * @return User
     * @throws NotFoundHttpException
     */
    protected function findModel($name) {
        if (($model = User::findOne(['name' => $name])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionSignup() {
        $model = new User([
            'scenario' => 'signup'
        ]);

        $bundle = [];
        if (!empty($_GET)) {
            $attributes = $model->activeAttributes();
            foreach ($_GET as $key => $value) {
                if (in_array($key, $attributes)) {
                    $model->$key = $value;
                } else {
                    $bundle[$key] = $value;
                }
            }
        }

        if ($model->load(Yii::$app->request->post())) {
            $bundle_post = Yii::$app->request->post('bundle');
            if ($bundle_post) {
                $bundle = array_merge($bundle_post, $bundle);
            }

            if (preg_match('|U\w{7}|', $model->name)) {
                $model->addError('name', Yii::t('app', Yii::t('app', 'Username cannot be in the format of Perfect Money wallet')));
            } elseif ($model->validate()) {
                $model->generateCode();
                $model->status = User::PLAIN;
                $model->setBundleFromAttributes(['hash'], true, $bundle);
                $model->save(false);
                $url = Url::to(['email', 'code' => $model->code], true);
                if ($model->sendEmail([
                    'subject' => Yii::$app->params['site']['name'] . ' ' . Yii::t('app', 'Signup'),
                    'content' => Yii::t('app', 'To confirm your registration click on the <a href="{url}">link</a>', [
                        'url' => $url,
                    ])
                ])
                ) {
                    Yii::$app->session->setFlash('info', Yii::t('app', 'Check your email'));
                } else {
                    Yii::$app->session->setFlash('error', Yii::t('app', 'Email send error'));
                }
                return $this->redirect(['home/index']);
            }
        }

        return $this->render('create', [
            'model' => $model,
            'bundle' => $bundle
        ]);
    }

    public function actionLogin() {
        $model = new Login();

        if ($model->load(Yii::$app->request->post())) {
            $user = $model->getUser();
            if ($user) {
                if (empty($user->hash)) {
                    Yii::$app->session->setFlash('error', Yii::t('app',
                        Yii::t('app', 'Your account is not activated. Check your email')));
                }
                else {
                    $can = $user->canLogin();
                    if ($can && $user->validatePassword($model->password)) {
                        if ($user->status > 0) {
                            if (empty($user->auth)) {
                                $user->generateAuthKey();
                                $user->save();
                            }
                            if (Yii::$app->user->login($user, $model->remember ? $user->duration * 60 : 0)) {
                                $bundle = $user->getBundle();
                                if ($bundle && isset($bundle['node_id'])) {
                                    $node_id = (int) $bundle['node_id'];
                                    $user->setBundle(null);
                                    $user->save();
                                    if (Node::find()->where(['id' => $node_id])->count() > 0) {
                                        Yii::$app->session->addFlash('success', Yii::t('app', 'Congratulation! You receive a gift'));
                                        return $this->redirect(['/pyramid/node/index', 'id' => $node_id]);
                                    }
                                }
                                return $this->redirect(['view']);
//                                return $this->actionView($user->name);
                            }
                            else {
                                Yii::$app->session->addFlash('error', Yii::t('app', 'Something wrong happened'));
                            }
                        } else {
                            Yii::$app->session->setFlash('error', Yii::t('app', Yii::t('app', 'Your account is blocked')));
                        }
                    } else {
                        Journal::write('user', 'login_fail', $user->id);
                        if ($can) {
                            Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
                        } else {
                            $record = Record::find()->where([
                                'object_id' => $user->id,
                                'event' => 'login_fail'

views/home/error.php
<?php
/**
 * @link http://zenothing.com/
*/

use yii\helpers\Html;

/* @var $exception \app\JournalException */

$this->title = $exception->event;
?>
<div class="site-error">
    <h1><?= Html::encode($this->title) ?></h1>
</div>

views/home/index.php
<?php
/**
 * @link http://zenothing.com/
 * @var yii\web\View $this
 * @var string $statistics
 * @var string $marketing
 */

use app\modules\article\models\Article;
use app\modules\feedback\controllers\FeedbackController;
use app\modules\pyramid\models\Type;
use app\widgets\Ext;
use yii\helpers\Html;
use yii\web\JqueryAsset;

$this->title = Yii::$app->name;

$benefits = [
    'Доступный вход',
    'Никаких приглашений',
    'Моментальные выплаты'
];

$this->registerMetaTag([
    'name' => 'description',
    'content' => implode(' ⬤ ', $benefits)
]);

/**
 * @param string $name
 * @param boolean|string $title
 * @return string
 */
function article($name, $title = null) {
    $model = Article::findOne(['name' => $name]);
    $content = Yii::$app->view->renderFile('@app/modules/article/views/article/view.php', [
        'model' => $model,
        'title' => $title
    ]);

    return null === $title ? $content : [
        'model' => $model,
        'content' => $content
    ];
}

$steps_title = [];
$steps_content = [];
foreach(['step1', 'step2', 'step3'] as $step) {
    $article = article($step, false);
    $steps_title[] = Html::tag('th', $article['model']->title);
    $steps_content[] = Html::tag('td', $article['content']);
}

?>
<div class="home-index">
    <?= Ext::stamp() ?>

    <div class="index-row">
        <div class="border">


            <div class="quo">
                <h1>Преимущества</h1>
                <table>
                    <tr>
                        <td><div id="one">ОБЩАЯ ОЧЕРЕДЬ!
                                КАЖДЫЙ ТИП СТОЛА ЯВЛЯЕТСЯ ОБЩЕЙ ОЧЕРЕДЬЮ...
                                РАБОТАЕТ ПРИНЦИП "ВСЕ-ПОМОГАЮТ-ВСЕМ!" </div></td><td><div id="two">РЕИНВЕСТ В КАЖДОМ СТОЛЕ!

                                ПОСЛЕ ВЫХОДА ИЗ СТОЛА, ВЫ АВТОМАТИЧЕСКИ ВОЗВРАЩАЕТЕСЬ
                                ВНИЗ ОЧЕРЕДИ В ЭТОТ ЖЕ СТОЛ!
                                ТЕМ САМЫМ ВЫ ВО ВСЕХ СТОЛАХ БУДЕТЕ ИМЕТЬ ДОПОЛНИТЕЛЬНОЕ МЕСТО,
                                ЧТО ДАЕТ ВАМ ВОЗМОЖНОСТЬ ЗАРАБАТЫВАТЬ ПОСТОЯННО!</div></td><td><div id="three">ПАССИВНЫЙ ДОХОД!
                                ДАЖЕ ЕСЛИ ВЫ НИКОГО НЕ ПРИГЛАСИЛИ,
                                СТОЛЫ БУДУТ ЗАКРЫВАТЬСЯ БЛАГОДАРЯ ОБЩЕЙ ОЧЕРЕДИ!</div></td>
                    </tr>
                    <tr>
                        <td><div id="four">АКТИВНЫЙ ДОХОД!
                                ПРЕДУСМОТРЕНА РЕФЕРАЛЬНАЯ СИСТЕМА-5% ОТ СУММЫ ВХОДА ВАШЕГО ПРИГЛАШЕННОГО,
                                НА ЛЮБОЙ ИЗ СТОЛОВ!</div></td><td><div id="five">ВАША СТАБИЛЬНОСТЬ!
                                ПОЧУСТВУЙТЕ ПО-НАСТОЯЩЕМУ СТАБИЛЬНЫЙ ДОХОД,
                                ОТ ПОСТОЯННОГО ВЫХОДА И РЕИНВЕСТА ВО ВСЕХ ПРОГРАММАХ!</div></td><td><div id="six"><b>ОСТАВАЙТЕСЬ С НАМИ!<br>ВМЕСТЕ МЫ СИЛА!</b></div></td>
                    </tr>
                </table>
            </div>


        </div>
        <div class="stat">
            <h1>Статистика</h1>
            <?= $statistics ?>
        </div>
        <div class="plans">
            <div>
                <?= article('marketing') ?>
            </div>
            <?php if (Yii::$app->user->isGuest): ?>
            <div class="more button"><?= Html::a(Yii::t('app', 'Signup'), ['user/signup'], ['class' => 'signup']) ?></div>
        </div>
        <?php endif; ?>
        <div></div>
    </div>

</div>

views/home/page.php
<?php
/**
 * @link http://zenothing.com/
*/
use yii\bootstrap\Html;

$title = $model->getTitle();
if ($title) {
    $this->title = $title;
}
?>
<div class="page">
    <?php
    if (!Yii::$app->user->isGuest && Yii::$app->user->identity->isManager()) {
        echo Html::a(Yii::t('app', 'Update'), ['update', 'name' => $model->name], ['class' => 'btn btn-primary']);
    }
    ?>

    <article><?= $model->content ?></article>
</div>

views/home/settings.php
<?php
/**
 * @link http://zenothing.com/
 * @var string[] $settings
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

echo Html::beginTag('div');
$form = ActiveForm::begin();
foreach($settings as $key => $value) {
    if ('_' != $key[0]) {
        echo Html::tag('div',
            Html::label(Yii::t('app', $key)) .
            Html::textInput($key, $value, ['class' => 'form-control']),
            ['class' => 'form-group']);
    }
}

echo Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success']);
ActiveForm::end();
echo Html::endTag('div');

views/home/statistics.php
<?php
/**
 * @link http://zenothing.com/
 */
use yii\helpers\Html;
?>
<div class="statistics">
    <table>
        <?php
        foreach($statistics as $name => $value) {
            echo Html::tag('tr', Html::tag('td', Yii::t('app', $name) . ':') . Html::tag('td', $value));
        }
        ?>
    </table>
</div>

views/home/update.php
<?php
/**
 * @link http://zenothing.com/
*/

use dosamigos\ckeditor\CKEditor;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Article */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="post-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= Html::activeHiddenInput($model, 'name') ?>
    <?= $form->field($model, 'content')->widget(CKEditor::class, [
        'preset' => 'full'
    ]) ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('app', 'Update'), ['class' => 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>